name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: cargo test --locked

      - name: Determine release version
        id: version
        run: |
          TAG_VERSION="${GITHUB_REF_NAME#v}"
          CARGO_VERSION=$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name=="dbt-lint-yaml") | .version')

          if [ "$TAG_VERSION" != "$CARGO_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match Cargo.toml version ($CARGO_VERSION)" >&2
            exit 1
          fi

          echo "version=$TAG_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build release binary
        run: cargo build --release --locked

      - name: Package artifacts
        run: |
          VERSION=${{ steps.version.outputs.version }}
          mkdir -p dist
          cp target/release/dbt-lint-yaml dist/dbt-lint-yaml
          tar -C dist -czf dbt-lint-yaml-${VERSION}-linux-x86_64.tar.gz dbt-lint-yaml
          rm dist/dbt-lint-yaml
          echo "artifact=dbt-lint-yaml-${VERSION}-linux-x86_64.tar.gz" >> "$GITHUB_ENV"

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: ${{ env.artifact }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
